In [9]:
import json
import plotly.express as px
import numpy as np

In [46]:
file = open("07_2015_09_12.json", "r")
image_json = json.load(file)

print((image_json.keys()))

dict_keys(['date', 'RGB', 'plant_health', 'floods_or_burned', 'snow_ice_clouds', 'NDVI'])


In [47]:
image = np.array(image_json["RGB"], dtype=np.uint8)
fig = px.imshow(image)
fig.show()

In [31]:
img_rgb = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
					[[0, 255, 0], [0, 0, 255], [255, 0, 0]]
				   ], dtype=np.uint8)
print((img_rgb))		  
fig = px.imshow(img_rgb)
fig.show()

[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[  0 255   0]
  [  0   0 255]
  [255   0   0]]]
